### ISSUE TITLE
Git-ignoring the `.cargo` folder?

### ISSUE THREAD

**Issue by tombh** [Rust-GPU/cargo-gpu#53]
I have some fancy nightly features I like to enable for faster compiles, but they live in `.cargo/config.toml`. The trouble is that they depend on my specific CPU architecture, so they can't be committed to any repo. Here's an example:

```toml
# See: https://bevyengine.org/learn/quick-start/getting-started/setup

# Find your machines arch with `rustc -vV | sed -n 's|host: ||p'`
[target.aarch64-unknown-linux-gnu]
linker = "clang"
rustflags = [
  "-C", "link-arg=-fuse-ld=/usr/bin/mold",
  # (Nightly) Make the current crate share its generic instantiations
  "-Zshare-generics=y"
]

# Don't forget to:
# `rustup component add rustc-codegen-cranelift-preview --toolchain nightly`
[unstable]
codegen-backend = true
[profile.dev]
codegen-backend = "cranelift"
[profile.dev.package."*"]
codegen-backend = "llvm"
```

In this repo we use `.cargo/config.toml` for a `xtask` alias, so I can't add all those fancy nightly flags. I'd personally vote for ignoring the `.cargo` folder, but it's not a big deal, so I'm just making an issue to register my vote.
